const drinks = [
  {
    id: "espresso",
    name: "Espresso",
    emoji: "☕️",
    glass: "demitasse",
    espressoOz: 1.5,
    milkOz: 0,
    waterOz: 0,
    crema: "Bold",
    microfoam: "None",
    latteArt: false,
    milkRequired: false,
  },
  {
    id: "ristretto",
    name: "Ristretto",
    emoji: "⚡️",
    glass: "demitasse",
    espressoOz: 1.0,
    milkOz: 0,
    waterOz: 0,
    crema: "Silky",
    microfoam: "None",
    latteArt: false,
    milkRequired: false,
  },
  {
    id: "cortado",
    name: "Cortado",
    emoji: "🫶",
    glass: "gibraltar",
    espressoOz: 2.0,
    milkOz: 2.0,
    waterOz: 0,
    crema: "Balanced",
    microfoam: "Light",
    latteArt: true,
    milkRequired: true,
  },
  {
    id: "flat-white",
    name: "Flat White",
    emoji: "🪶",
    glass: "ceramic",
    espressoOz: 2.0,
    milkOz: 5.0,
    waterOz: 0,
    crema: "Integrated",
    microfoam: "Silky",
    latteArt: true,
    milkRequired: true,
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    emoji: "🌤️",
    glass: "cup",
    espressoOz: 2.0,
    milkOz: 4.0,
    waterOz: 0,
    crema: "Defined",
    microfoam: "Thick",
    latteArt: true,
    milkRequired: true,
  },
  {
    id: "latte",
    name: "Latte",
    emoji: "🎨",
    glass: "tall",
    espressoOz: 2.0,
    milkOz: 8.0,
    waterOz: 0,
    crema: "Soft",
    microfoam: "Glossy",
    latteArt: true,
    milkRequired: true,
  },
  {
    id: "americano",
    name: "Americano",
    emoji: "🧊",
    glass: "tumbler",
    espressoOz: 2.0,
    milkOz: 0,
    waterOz: 6.0,
    crema: "Light",
    microfoam: "None",
    latteArt: false,
    milkRequired: false,
  },
  {
    id: "long-black",
    name: "Long Black",
    emoji: "🌊",
    glass: "tumbler",
    espressoOz: 2.0,
    milkOz: 0,
    waterOz: 5.0,
    crema: "Lifted",
    microfoam: "None",
    latteArt: false,
    milkRequired: false,
  },
];

module.exports = (req, res) => {
  if (req.method !== "GET") {
    res.setHeader("Allow", "GET");
    return res.status(405).json({ error: "Method not allowed" });
  }

  return res.status(200).json({ drinks });
};
